name: Build and Sign Android APK

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Устанавливаем Java 17
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Устанавливаем Node.js и Cordova
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cordova
      run: npm install -g cordova

    # 4. Устанавливаем Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        target: android-34

    # 5. Создаем Cordova проект и выполняем сборку APK
    - name: Build APK
      run: |
        cordova platform add android
        cordova build android --release -- --packageType=apk

    # Проверяем существование файла APK
    - name: Check APK exists
      run: |
        if [ -f platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ]; then
          echo "APK найден, продолжаем подписывать."
        else
          echo "APK не найден, проверьте процесс сборки."
          exit 1
        fi

    # 6. Автоматическое создание keystore
    - name: Generate keystore
      run: |
        keytool -genkey -v \
          -keystore my-release-key.keystore \
          -storepass qwerty \
          -keypass qwerty \
          -alias qwerty \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000

    # 7. Подпись APK
    - name: Sign APK
      run: |
        jarsigner -verbose \
          -keystore my-release-key.keystore \
          -storepass qwerty \
          -keypass qwerty \
          platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          qwerty

    # 8. Выравнивание APK (zipalign)
    - name: Align APK
      run: |
        zipalign -v 4 \
          platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          app-release.apk

    # 9. Загружаем готовый APK как артефакт
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app-release.apk