name: Build and Sign Android APK

on: push

env:
  APP_NAME: "com.construct.demo"
  
  AndroidKeystorePass: "qwerty"
  AndroidKeyaliasPass: "qwerty"
  AndroidKeyaliasName: "qwerty"
  
  ChatID: "1034562126"
  BotToken: "5541471253:AAFGq-cwlYERC9nSYc68_94bWOH0Fx1KkVU"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Устанавливаем Java 17
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Устанавливаем Node.js и Cordova
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cordova
      run: npm install -g cordova

    # 4. Устанавливаем Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        target: android-34

    # 6. Выполняем сборку APK
    - name: Build APK
      run: |
        cordova platform add android
        cordova build android --release -- --packageType=apk

    # 7. Проверяем наличие APK
    - name: Check APK exists
      run: |
        if [ -f platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ]; then
          echo "APK найден, продолжаем подписывать."
        else
          echo "APK не найден, проверьте процесс сборки."
          exit 1
        fi

    # 8. Создаем keystore
    - name: Generate keystore
      run: |
        keytool -genkey -v \
          -keystore my-release-key.keystore \
          -storepass ${{ env.AndroidKeystorePass }} \
          -keypass ${{ env.AndroidKeyaliasPass }} \
          -alias ${{ env.AndroidKeyaliasName }} \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -dname "CN=John Doe, OU=Development, O=Example Inc., L=New York, ST=NY, C=US"

    # 9. Подписываем APK
    - name: Sign APK
      run: |
        jarsigner -verbose \
          -keystore my-release-key.keystore \
          -storepass qwerty \
          -keypass qwerty \
          platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          qwerty

    # 10. Выравниваем APK
    - name: Align APK
      run: |
        zipalign -v 4 \
          platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ env.APP_NAME }}.apk

    # 11. Загружаем подписанный APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APP_NAME }}.apk
        path: ${{ env.APP_NAME }}.apk
        
    # 12. Отправляем APK в Telegram
    - name: Send APK to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ env.ChatID }}
        token: ${{ env.BotToken }}
        message: " "
        document: '${{ env.APP_NAME }}.apk'