name: Build Android APK and AAB

on: push

env:
  APP_NAME: "com.construct.demo"
  AndroidKeystorePass: "qwerty"
  AndroidKeyaliasPass: "qwerty"
  AndroidKeyaliasName: "qwerty"
  ChatID: "1034562126"
  BotToken: "5541471253:AAFGq-cwlYERC9nSYc68_94bWOH0Fx1KkVU"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Устанавливаем Java 17
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Устанавливаем Node.js и Cordova
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cordova
      run: npm install -g cordova

    # 4. Устанавливаем Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        target: android-34

    # 5. Добавляем Build Tools в PATH
    - name: Add Build Tools to PATH
      run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

    # 6. Добавляем платформу Cordova
    - name: Add Android platform
      run: cordova platform add android

  build-apk:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    # 1. Скачиваем окружение
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Сборка APK
    - name: Build APK
      run: |
        cordova build android --release -- --packageType=apk
        mv platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ${{ env.APP_NAME }}.apk

    # 3. Загружаем APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APP_NAME }}.apk
        path: ${{ env.APP_NAME }}.apk

  build-aab:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    # 1. Скачиваем окружение
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Сборка AAB
    - name: Build AAB
      run: |
        cordova build android --release -- --packageType=bundle
        jarsigner -verbose \
          -keystore user.keystore \
          -storepass ${{ env.AndroidKeystorePass }} \
          -keypass ${{ env.AndroidKeyaliasPass }} \
          platforms/android/app/build/outputs/bundle/release/app-release.aab \
          ${{ env.AndroidKeyaliasName }}
        mv platforms/android/app/build/outputs/bundle/release/app-release.aab ${{ env.APP_NAME }}.aab

    # 3. Загружаем AAB
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APP_NAME }}.aab
        path: ${{ env.APP_NAME }}.aab

  send-to-telegram:
    runs-on: ubuntu-latest
    needs:
      - build-apk
      - build-aab

    steps:
    # 1. Скачиваем артефакты
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    # 2. Отправляем APK и AAB в Telegram
    - name: Send APK and AAB to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ env.ChatID }}
        token: ${{ env.BotToken }}
        message: "Собраны APK и подписанный AAB для вашего приложения."
        document: |
          artifacts/${{ env.APP_NAME }}.apk
          artifacts/${{ env.APP_NAME }}.aab